name: django-3.2.19
channels:
  - defaults
dependencies:
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - openssl=1.1.1t
  - pip=22.3.1
  - python=3.7.16
  - setuptools=65.6.3
  - sqlite=3.41.2
  - vc=14.2
  - vs2015_runtime
  - wheel=0.38.4=
  - wincertstore=0.2
  - pip:
      - asgiref==3.7.1
      - backcall==0.2.0
      - colorama==0.4.6
      - decorator==5.1.1
      - django==3.2.19
      - ipython==7.34.0
      - jedi==0.18.2
      - matplotlib-inline==0.1.6
      - mysql-connector==2.2.9
      - parso==0.8.3
      - pickleshare==0.7.5
      - prompt-toolkit==3.0.38
      - pygments==2.15.1
      - pymysql==1.0.3
      - pytz==2023.3
      - sqlparse==0.4.4
      - traitlets==5.9.0
      - typing-extensions==4.6.2
      - wcwidth==0.2.6